#!/bin/bash

#
# This file is part of ATSDB.
#
# ATSDB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ATSDB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with ATSDB.  If not, see <http://www.gnu.org/licenses/>.
#

PROGNAME=`basename $0`
ATSDB=
DEBUG=

INPUT_FILE=
INPUT_HOURS="0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23"

CSV_HDR="REC_NUM;POS_LAT_DEG;POS_LONG_DEG;TOD;TARGET_ADDR;MODE3A_CODE;ALT_BARO_FT;CALLSIGN;POSITION_ACCURACY;EMITTER_CATEGORY;GROUND_BIT;DS_ID;GROUNDSPEED_KT;TRACK_ANGLE_DEG;BARO_VERTICAL_RATE_FTM;ALT_GEO_FT;FINAL_SEL_ALTITUDE_FT"

help() {
       cat <<EOF
USAGE: $PROGNAME -f <filename> [-t <hours>] [-a] [-d] [-h]
   -f <filename> ::= compressed ADS-B exchange file ( .zip )
   -t <hours>    ::= hours to parse (comma separated list of HH)
      ex: 1,4,11
   -a ::= prepare output for ATSDB (CSV format)
   -d ::= debug mode
   -h     This help
EOF
}

if [ $# -lt 1 ]; then
   help
   exit 1
fi

while getopts "adhf:t:" opt
  do
  case "$opt" in
      f) INPUT_FILE="$OPTARG" ;;
      t) INPUT_HOURS="$OPTARG" ;;
      a) ATSDB="-a" ;;
      d) DEBUG="-d" ;;
      h) help; exit 0 ;;
      *) help; exit 2 ;;
  esac
done

ADSB_FILE=`basename $INPUT_FILE | sed 's/\.zip$//g'`

for h in `echo $INPUT_HOURS | tr ',' ' '`
do
   HOUR=`printf "%.2d" $h`
   echo "parsing hour: $HOUR"
   if [ ! -d "$ADSB_FILE/$HOUR" ]; then
      mkdir -p $ADSB_FILE/$HOUR
   fi
   unzip -d $ADSB_FILE/$HOUR $INPUT_FILE "${ADSB_FILE}-${HOUR}??Z.json"
   (cd $ADSB_FILE/$HOUR; \
    parseADSBxchg -f $ADSB_FILE $ATSDB $DEBUG; \
    rm *.json; \
    if [ ! -z "$ATSDB" ]; then \
       echo $CSV_HDR > ADS-Bxchg.$ADSB_FILE.csv; \
    fi; \
    grep -vh REC_NUM ADS-B/*.csv >> ADS-Bxchg.$ADSB_FILE.csv)
done
